set -g mouse on

# Sane~ish splits
bind v split-window -h -c "#{pane_current_path}"
bind h split-window -v -c "#{pane_current_path}"

# Session continuity
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# Statusbar
# Caveat: `brew install bash` for proper colors
set -g @plugin '2kabhishek/tmux2k'
set -g @tmux2k-theme 'monokai'
set -g @tmux2k-icons-only true

# Auto-install TPM
if "test ! -d ~/.tmux/plugins/tpm" "run 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins'"

# Run TPM
run '~/.tmux/plugins/tpm/tpm'